/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActiveExperiment
 */
export interface ActiveExperiment {
    /**
     * 
     * @type {boolean}
     * @memberof ActiveExperiment
     */
    currentlyActive: boolean;
}

/**
 * Check if a given object implements the ActiveExperiment interface.
 */
export function instanceOfActiveExperiment(value: object): value is ActiveExperiment {
    if (!('currentlyActive' in value) || value['currentlyActive'] === undefined) return false;
    return true;
}

export function ActiveExperimentFromJSON(json: any): ActiveExperiment {
    return ActiveExperimentFromJSONTyped(json, false);
}

export function ActiveExperimentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActiveExperiment {
    if (json == null) {
        return json;
    }
    return {
        
        'currentlyActive': json['currently_active'],
    };
}

export function ActiveExperimentToJSON(json: any): ActiveExperiment {
    return ActiveExperimentToJSONTyped(json, false);
}

export function ActiveExperimentToJSONTyped(value?: ActiveExperiment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currently_active': value['currentlyActive'],
    };
}

