/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogsResponse
 */
export interface LogsResponse {
    /**
     * 
     * @type {string}
     * @memberof LogsResponse
     */
    experimentId: string;
    /**
     * 
     * @type {number}
     * @memberof LogsResponse
     */
    systemId: number;
    /**
     * 
     * @type {Date}
     * @memberof LogsResponse
     */
    timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof LogsResponse
     */
    value: string;
    /**
     * 
     * @type {number}
     * @memberof LogsResponse
     */
    id: number;
}

/**
 * Check if a given object implements the LogsResponse interface.
 */
export function instanceOfLogsResponse(value: object): value is LogsResponse {
    if (!('experimentId' in value) || value['experimentId'] === undefined) return false;
    if (!('systemId' in value) || value['systemId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function LogsResponseFromJSON(json: any): LogsResponse {
    return LogsResponseFromJSONTyped(json, false);
}

export function LogsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'experimentId': json['experiment_id'],
        'systemId': json['system_id'],
        'timestamp': (new Date(json['timestamp'])),
        'value': json['value'],
        'id': json['id'],
    };
}

export function LogsResponseToJSON(json: any): LogsResponse {
    return LogsResponseToJSONTyped(json, false);
}

export function LogsResponseToJSONTyped(value?: LogsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'experiment_id': value['experimentId'],
        'system_id': value['systemId'],
        'timestamp': ((value['timestamp']).toISOString()),
        'value': value['value'],
        'id': value['id'],
    };
}

