/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogsCreate
 */
export interface LogsCreate {
    /**
     * 
     * @type {string}
     * @memberof LogsCreate
     */
    experimentId: string;
    /**
     * 
     * @type {number}
     * @memberof LogsCreate
     */
    systemId: number;
    /**
     * 
     * @type {Date}
     * @memberof LogsCreate
     */
    timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof LogsCreate
     */
    value: string;
}

/**
 * Check if a given object implements the LogsCreate interface.
 */
export function instanceOfLogsCreate(value: object): value is LogsCreate {
    if (!('experimentId' in value) || value['experimentId'] === undefined) return false;
    if (!('systemId' in value) || value['systemId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function LogsCreateFromJSON(json: any): LogsCreate {
    return LogsCreateFromJSONTyped(json, false);
}

export function LogsCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogsCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'experimentId': json['experiment_id'],
        'systemId': json['system_id'],
        'timestamp': (new Date(json['timestamp'])),
        'value': json['value'],
    };
}

export function LogsCreateToJSON(json: any): LogsCreate {
    return LogsCreateToJSONTyped(json, false);
}

export function LogsCreateToJSONTyped(value?: LogsCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'experiment_id': value['experimentId'],
        'system_id': value['systemId'],
        'timestamp': ((value['timestamp']).toISOString()),
        'value': value['value'],
    };
}

