/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemCreate
 */
export interface SystemCreate {
    /**
     * 
     * @type {string}
     * @memberof SystemCreate
     */
    name: string;
}

/**
 * Check if a given object implements the SystemCreate interface.
 */
export function instanceOfSystemCreate(value: object): value is SystemCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SystemCreateFromJSON(json: any): SystemCreate {
    return SystemCreateFromJSONTyped(json, false);
}

export function SystemCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function SystemCreateToJSON(json: any): SystemCreate {
    return SystemCreateToJSONTyped(json, false);
}

export function SystemCreateToJSONTyped(value?: SystemCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

