/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UISettingsResponse
 */
export interface UISettingsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof UISettingsResponse
     */
    distanceText: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UISettingsResponse
     */
    distanceLine: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UISettingsResponse
     */
    landmarks: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UISettingsResponse
     */
    fixtures: boolean;
    /**
     * 
     * @type {number}
     * @memberof UISettingsResponse
     */
    id: number;
}

/**
 * Check if a given object implements the UISettingsResponse interface.
 */
export function instanceOfUISettingsResponse(value: object): value is UISettingsResponse {
    if (!('distanceText' in value) || value['distanceText'] === undefined) return false;
    if (!('distanceLine' in value) || value['distanceLine'] === undefined) return false;
    if (!('landmarks' in value) || value['landmarks'] === undefined) return false;
    if (!('fixtures' in value) || value['fixtures'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UISettingsResponseFromJSON(json: any): UISettingsResponse {
    return UISettingsResponseFromJSONTyped(json, false);
}

export function UISettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UISettingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'distanceText': json['distance_text'],
        'distanceLine': json['distance_line'],
        'landmarks': json['landmarks'],
        'fixtures': json['fixtures'],
        'id': json['id'],
    };
}

export function UISettingsResponseToJSON(json: any): UISettingsResponse {
    return UISettingsResponseToJSONTyped(json, false);
}

export function UISettingsResponseToJSONTyped(value?: UISettingsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'distance_text': value['distanceText'],
        'distance_line': value['distanceLine'],
        'landmarks': value['landmarks'],
        'fixtures': value['fixtures'],
        'id': value['id'],
    };
}

